name: Deployment to Testing Environment

on:
  workflow_run:
    workflows: ["Code Testing and Build Check"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add necessary steps for deployment
      - name: Deploy to Testing Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USERNAME }}
          password: ${{ secrets.TEST_SERVER_PASSWORD }}
          script: |
            cd /path/to/your/application
            git pull origin main
            # Additional deployment steps (e.g., restart server, install dependencies, etc.)
